using DelimitedFiles
data1 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-11.000000.dat")
data2 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-20.000000.dat")
data3 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-30.000000.dat")
data4 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-40.000000.dat")
data5 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-50.000000.dat")
data6 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-60.000000.dat")
data7 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-70.000000.dat")
data8 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-80.000000.dat")
data9 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-90.000000.dat")
data10 = readdlm("/home/pushkar/Task_assignment_pics/AllenCahn2DFDM/Output-100.000000.dat")
d = [data1 data2 data3 data4 data5 data6 data7 data8 data9 data10]
using Plots;pyplot()
heatmap(data1,c=:greys)
heatmap(data2,c=:greys)
heatmap(data3,c=:greys)
heatmap(data4,c=:greys)
heatmap(data5,c=:greys)
heatmap(data6,c=:greys)
heatmap(data6,c=:greys)
heatmap(data7,c=:greys)
heatmap(data8,c=:greys)
heatmap(data9,c=:greys)
heatmap(data10,c=:greys)
